apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  namespace: airflow
type: Opaque
data:
  webserver-secret-key: WEBSERVER_SECRET_KEY # Replace with base64-encoded value
  # webserver-secret-key: V0VCU0VSVkVSX1NFQ1JFVF9LRVkK