apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # dags folder on cluster (mounted dags folder in minikube not in local machine)
    path: "/mnt/airflow/dags"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/airflow/logs"